name: NodeJS

on:
  push:
    branches: [main]
  pull_request:

jobs:

  complete:
    if: always()
    needs: [build-and-test]
    runs-on: ubuntu-latest
    steps:
      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: stellar/actions/rust-cache@main
      - run: rustup update
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo install --locked stellar-cli --features opt


      - run: make build

      # Setup Node.js with caching
      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.0
          cache: 'npm'

      - run: |
          mkdir -p .soroban-example-dapp
          echo 'testnet' > .soroban-example-dapp/network
          echo 'CAU23MVDEW7VMB3AXC5PL5GZO3HBYZPEIP2P46X4T3AIC4Y7FXYZWES5' > .soroban-example-dapp/abundance_token_id
          echo 'CDJPYH5HNGZ24SEWXFJOW6RXXHHNKU4XPCPBMB2VRTDPTMVPLYFQKZIE' > .soroban-example-dapp/crowdfund_id
          echo 'Test SDF Network ; September 2015' > .soroban-example-dapp/passphrase
          echo 'https://soroban-testnet.stellar.org/' > .soroban-example-dapp/rpc-url
          echo '{"network":"testnet","rpcUrl":"https://soroban-testnet.stellar.org","networkPassphrase":"Test SDF Network ; September 2015"}' > shared/config.json

      - run: npm ci

      - run: npx next build
